    name: Deploy to Production
    
    on:
      push:
        branches:
          - main
    
    defaults: 
        run: 
            working-directory: ./volvo
    jobs:
      deploy:
        name: Build, Deploy to S3 bucket
        runs-on: [ubuntu-latest]
    
        strategy:
          matrix:
            node-version: [14.4.x]
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
            
          - name: Npm install
            run: npm install
    
          - name: Build
            run: DISABLE_ESLINT_PLUGIN=true npm run build

          
          - name: Deploy                  
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            run: |
                aws s3 cp \
                --recursive \
                --region ap-northeast-2 \
                build s3://apply.entrydsm.hs.kr

#           - name: Transfer to S3 for serving static
#             uses: jakejarvis/s3-sync-action@master
#             with:
#               args: --acl public-read --follow-symlinks --delete
#             env:
#               AWS_S3_BUCKET: apply.entrydsm.hs.kr
#               AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
#               AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
#               AWS_REGION: ap-northeast-2
#               SOURCE_DIR: 'build'
